require "v2/Factory/Recipe"

return {
  things = {
    Acetaldehyde  = { __type = "Fluid", id = "immersiveengineering:acetaldehyde",   name="Acetaldehyde" } as Fluid,
    PhelonicResin = { __type = "Fluid", id = "immersiveengineering:phenolic_resin", name="Phenolic Resin" } as Fluid,

    Duroplast     = { __type = "Item", id = "immersiveengineering:plate_duroplast", name = "Duroplast Plate" } as Item,
  }
}